# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b64e80b30b0dfc087887cd0a6207bbe12f12174ead46c0caa739fbb36bf858b55cefa4dce0cc9daad096cb6aaac0713784a1e64431259c9d38306dc1d970be4

test:
  secret_key_base: ed8eb199476f1b6e206e11e9257fdfa42fe9050e38cacacd9caa3af97ef6cfd174d3c764023e33419afd0553171c31dd7c52c1d4b460dfcb366f6333ed8d64e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
